name: FastApi Backend
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make install-backend

      - name: Format code
        run: make format-backend

      - name: Lint with pylint
        run: make lint-backend

      - name: Test with pytest
        run: make test-backend

      - name: Build Container
        run: make build-backend
        